# Generated by Django 4.2.5 on 2023-09-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='actividad_imagenes/')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(max_length=100)),
                ('imagen_env', models.FileField(blank=True, null=True, upload_to='evaluacion_imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_mod', models.CharField(max_length=100)),
                ('instrucciones', models.CharField(max_length=255)),
                ('imagen_mod', models.FileField(blank=True, null=True, upload_to='modulo_imagenes/')),
                ('tipo_multimedia', models.CharField(max_length=100)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('grado_ac', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(choices=[('opcion1', 'Opción 1'), ('opcion2', 'Opción 2')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEvaluaciones',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('competencia_1', models.IntegerField()),
                ('competencia_2', models.IntegerField()),
                ('competencia_3', models.IntegerField()),
                ('competencia_4', models.IntegerField()),
                ('competencia_5', models.IntegerField()),
                ('id_evaluacion', models.OneToOneField(db_column='id_evaluacion', on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.evaluaciones')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoUsuarios',
            fields=[
                ('id_progreso_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('estado_actividad', models.BooleanField(default=False)),
                ('estado_modulo', models.BooleanField(default=False)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.actividades')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.modulos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoActividades',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('actividad1', models.BooleanField(default=False)),
                ('actividad2', models.BooleanField(default=False)),
                ('actividad3', models.BooleanField(default=False)),
                ('actividad4', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaModulos',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_res', models.FileField(blank=True, null=True, upload_to='evidencia_archivos/')),
                ('id_modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.modulos')),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('actividades', models.IntegerField()),
                ('evidencias', models.IntegerField()),
                ('progreso', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEL4c_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('estadisticas', models.ManyToManyField(to='SEL4c_app.estadisticas')),
                ('evidencias_modulos', models.ManyToManyField(to='SEL4c_app.evidenciamodulos')),
                ('progreso_actividades', models.ManyToManyField(to='SEL4c_app.progresoactividades')),
                ('resultados_evaluaciones', models.ManyToManyField(to='SEL4c_app.resultadoevaluaciones')),
            ],
        ),
    ]
