# Generated by Django 4.2.4 on 2023-09-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEL4c_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulos',
            name='instrucciones',
            field=models.CharField(max_length=2000),
        ),
    ]
